apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dreiahitm-medt-fileupload-pvc
  namespace: student-m-puchner
  labels:
    app: dreiahitm-medt
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi