name: php

on:
  push:
  workflow_dispatch:

jobs:
  php-app:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 3ahitm-medt-backend
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      SERVER_URL: ${{ secrets.SERVER_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: build app
        run: php ./betterphp/cli/index.php
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . --tag $IMAGE_NAME --build-arg "DB_HOST=${{ secrets.DB_HOST }}" --build-arg "DB_USER=${{ secrets.DB_USER }}" --build-arg "DB_PASS=${{ secrets.DB_PASS }}" --build-arg "DB_NAME=${{ secrets.DB_NAME }}" --build-arg "DB_PORT=${{ secrets.DB_PORT }}" --build-arg "SERVER_URL=${{ secrets.SERVER_URL }}" \
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

